/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * 中文文档
 * 开发文档
 * OpenAPI spec version: 1.0
 */
export type PostControllerGetByPage200AllOf = {
  data?: PostDto[];
};

export type PostControllerGetByPage200 = ResponseResult & PostControllerGetByPage200AllOf;

export type PostControllerFindAll200AllOf = {
  data?: PostDto[];
};

export type PostControllerFindAll200 = ResponseResult & PostControllerFindAll200AllOf;

export type PostControllerCreate200AllOf = {
  data?: String;
};

export type PostControllerCreate200 = ResponseResult & PostControllerCreate200AllOf;

export type AnonymousControllerRemove200AllOf = {
  data?: String;
};

export type AnonymousControllerRemove200 = ResponseResult & AnonymousControllerRemove200AllOf;

export type AnonymousControllerFindAllByArticleId200AllOf = {
  data?: AnonymousDto[];
};

export type AnonymousControllerFindAllByArticleId200 = ResponseResult & AnonymousControllerFindAllByArticleId200AllOf;

export type AnonymousControllerCreate200AllOf = {
  data?: String;
};

export type AnonymousControllerCreate200 = ResponseResult & AnonymousControllerCreate200AllOf;

export type UploadControllerUploadImage200AllOf = {
  data?: UrlDto;
};

export type UploadControllerUploadImage200 = ResponseResult & UploadControllerUploadImage200AllOf;

export type UploadControllerUploadImageBody = {
  file?: Blob;
};

export type CommentControllerRemove200AllOf = {
  data?: String;
};

export type CommentControllerRemove200 = ResponseResult & CommentControllerRemove200AllOf;

export type CommentControllerFindAllByArticleId200AllOf = {
  data?: CommentDto[];
};

export type CommentControllerFindAllByArticleId200 = ResponseResult & CommentControllerFindAllByArticleId200AllOf;

export type CommentControllerCreate200AllOf = {
  data?: String;
};

export type CommentControllerCreate200 = ResponseResult & CommentControllerCreate200AllOf;

export type ArticleControllerRemove200AllOf = {
  data?: String;
};

export type ArticleControllerRemove200 = ResponseResult & ArticleControllerRemove200AllOf;

export type ArticleControllerUpdate200AllOf = {
  data?: String;
};

export type ArticleControllerUpdate200 = ResponseResult & ArticleControllerUpdate200AllOf;

export type ArticleControllerFindOneById200AllOf = {
  data?: ArticleDto;
};

export type ArticleControllerFindOneById200 = ResponseResult & ArticleControllerFindOneById200AllOf;

export type ArticleControllerFindOneByTitle200AllOf = {
  data?: ArticleDto[];
};

export type ArticleControllerFindOneByTitle200 = ResponseResult & ArticleControllerFindOneByTitle200AllOf;

export type ArticleControllerFindAll200AllOf = {
  data?: ArticleDto[];
};

export type ArticleControllerFindAll200 = ResponseResult & ArticleControllerFindAll200AllOf;

export type AdminControllerRemove200AllOf = {
  data?: String;
};

export type AdminControllerRemove200 = ResponseResult & AdminControllerRemove200AllOf;

export type AdminControllerUpdate200AllOf = {
  data?: String;
};

export type AdminControllerUpdate200 = ResponseResult & AdminControllerUpdate200AllOf;

export type AdminControllerFindOne200AllOf = {
  data?: AdminDto;
};

export type AdminControllerFindOne200 = ResponseResult & AdminControllerFindOne200AllOf;

export type AdminControllerFindAll200AllOf = {
  data?: AdminDto[];
};

export type AdminControllerFindAll200 = ResponseResult & AdminControllerFindAll200AllOf;

export type AdminControllerCreate200AllOf = {
  data?: String;
};

export type AdminControllerCreate200 = ResponseResult & AdminControllerCreate200AllOf;

export type AdminControllerDoLogin200AllOf = {
  data?: ResLoginDto;
};

export type AdminControllerDoLogin200 = ResponseResult & AdminControllerDoLogin200AllOf;

export type AppControllerGetRole200AllOf = {
  data?: String;
};

export type AppControllerGetRole200 = ResponseResult & AppControllerGetRole200AllOf;

export type AppControllerGetAuth200AllOf = {
  data?: String;
};

export type AppControllerGetAuth200 = ResponseResult & AppControllerGetAuth200AllOf;

export interface PostDto {
  id: number;
  name: string;
  handle: string;
  createTime: string;
  images: string;
  content: string;
}

export interface CreatePostDto {
  name: string;
  images: string;
  content: string;
}

export interface AnonymousDto {
  id: number;
  name: string;
  email: string;
  content: string;
  createTime: string;
}

export interface CreateAnonymousDto {
  name: string;
  email: string;
  content: string;
  targetId: number;
}

export interface UrlDto {
  message: string;
  imageUrl: string;
}

export interface CommentDto {
  id: number;
  content: string;
  admin: AdminDto;
  targetId: number;
  createTime: string;
}

export interface CreateCommentDto {
  content: string;
  adminId: number;
  targetId: number;
}

export interface UpdateArticleDto {
  title?: string;
  content?: string;
  image?: string;
}

export interface ArticleDto {
  id: number;
  title: string;
  createTime: string;
  updateTime: string;
  image: string;
  content: string;
}

export interface CreateArticleDto {
  title: string;
  content: string;
  image: string;
}

export interface UpdateAdminDto {
  name?: string;
  password?: string;
  phoneNumber?: string;
  gender?: string;
  role?: string;
}

export interface CreateAdminDto {
  name: string;
  password: string;
  phoneNumber: string;
  gender: string;
  role: string;
}

export interface LoginAdminDto {
  name: string;
  password: string;
}

export interface AdminDto {
  id: number;
  name: string;
  phoneNumber: string;
  createTime: string;
  gender: string;
  role: string;
}

export interface ResLoginDto {
  user: AdminDto;
  access_token: string;
}

export interface String { [key: string]: unknown }

export type ArticleControllerCreate200AllOf = {
  data?: String;
};

/**
 * 响应数据
 */
export type ResponseResultData = { [key: string]: unknown };

export interface ResponseResult {
  /** 响应状态码 */
  code: number;
  /** 响应消息 */
  msg: string;
  /** 响应数据 */
  data?: ResponseResultData;
  /** 响应时间 */
  timestamp: number;
}

export type ArticleControllerCreate200 = ResponseResult & ArticleControllerCreate200AllOf;

